# Generated by Django 5.2.7 on 2025-10-10 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('BAHAR-2024', 'Bahar 2024'), ('GÜZ-2024', 'Güz 2024'), ('BAHAR-2025', 'Bahar 2025'), ('GÜZ-2025', 'Güz 2025')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.faculty')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
