# Generated by Django 5.2.7 on 2026-03-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_uploade_82a951_idx',
            old_name='notes_note_uploaded_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_likes_ef81a2_idx',
            old_name='notes_note_likes_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_downloa_3d44e3_idx',
            old_name='notes_note_dl_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_univers_2714f3_idx',
            old_name='notes_note_uni_date_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_departm_798832_idx',
            old_name='notes_note_dept_date_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_course__8c1dea_idx',
            old_name='notes_note_course_date_idx',
        ),
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('BAHAR-2024', 'Bahar 2024'), ('GÜZ-2024', 'Güz 2024'), ('BAHAR-2025', 'Bahar 2025'), ('GÜZ-2025', 'Güz 2025'), ('BAHAR-2026', 'Bahar 2026'), ('GÜZ-2026', 'Güz 2026')], max_length=20),
        ),
    ]
