# Generated by Django 5.2.8 on 2025-11-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bölüm Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fakülte Adı')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Üniversite Adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uni_logos/')),
            ],
            options={
                'verbose_name': 'Üniversite',
                'verbose_name_plural': 'Üniversiteler',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ders Adı')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Ders Kodu')),
                ('class_year', models.IntegerField(choices=[(1, '1. Sınıf'), (2, '2. Sınıf'), (3, '3. Sınıf'), (4, '4. Sınıf'), (5, 'Hazırlık / Diğer')], default=1, verbose_name='Sınıf Seviyesi')),
                ('term_season', models.CharField(choices=[('Guz', 'Güz Dönemi'), ('Bahar', 'Bahar Dönemi'), ('Yaz', 'Yaz Okulu')], default='Guz', max_length=10, verbose_name='Dönem')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.department', verbose_name='Bölüm')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['class_year', 'term_season', 'name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academic.faculty', verbose_name='Fakülte'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Not Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('pdf_file', models.FileField(upload_to='notes/', verbose_name='PDF Dosyası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='İndirme')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Beğeni')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Onaylı')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.course', verbose_name='Ders')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen Öğrenci')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='academic.university', verbose_name='Üniversite'),
        ),
    ]
