# Generated by Django 5.2.7 on 2026-03-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='categories__departm_073de3_idx',
            old_name='categories_course_dept_name_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='categories__faculty_271c8e_idx',
            old_name='categories_dept_fac_name_idx',
        ),
        migrations.RenameIndex(
            model_name='faculty',
            new_name='categories__univers_60c4b6_idx',
            old_name='categories_faculty_uni_name_idx',
        ),
    ]
