# Generated by Django 5.2.7 on 2026-01-04 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0003_comment_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_note', 'İlk Not'), ('hundred_likes', '100 Beğeni'), ('thousand_downloads', '1000 İndirme'), ('seven_day_streak', '7 Gün Streak'), ('level_10', 'Level 10'), ('top_contributor', 'En Çok Katkı')], max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='XPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note_upload', 'Not Yükleme'), ('note_update', 'Not Güncelleme'), ('like_received', 'Beğeni Alınması'), ('download_received', 'İndirme Alınması'), ('favorite_received', 'Favori Alınması'), ('profile_complete', 'Profil Tamamlama'), ('daily_login', 'Günlük Giriş'), ('comment_made', 'Yorum Yapma'), ('note_deleted', 'Not Silme')], max_length=20)),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_activities', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP Aktivitesi',
                'verbose_name_plural': 'XP Aktiviteleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='rewards_xpa_user_id_c685f5_idx'), models.Index(fields=['activity_type', 'created_at'], name='rewards_xpa_activit_aa63d0_idx'), models.Index(fields=['user', 'activity_type', 'created_at'], name='rewards_xpa_user_id_335834_idx')],
            },
        ),
    ]
