# Generated by Django 5.2.7 on 2026-01-04 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_comment_like'),
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-earned_at']},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='note',
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('first_note', 'İlk Not'), ('first_like', 'İlk Beğeni'), ('first_download', 'İlk İndirme'), ('notes_10', '10 Not'), ('notes_50', '50 Not'), ('notes_100', '100 Not'), ('likes_100', '100 Beğeni'), ('downloads_1000', '1000 İndirme'), ('level_5', 'Seviye 5'), ('level_10', 'Seviye 10'), ('daily_streak_7', '7 Gün Seri'), ('daily_streak_30', '30 Gün Seri')], max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('note_created', 'Not Oluşturma'), ('note_updated', 'Not Güncelleme'), ('like_received', 'Beğeni Alınması'), ('download_received', 'İndirme Alınması'), ('favorite_received', 'Favoriye Eklenme'), ('profile_completed', 'Profil Tamamlama'), ('daily_login', 'Günlük Giriş'), ('penalty_spam', 'Spam Cezası'), ('penalty_low_quality', 'Düşük Kalite Cezası')], max_length=30)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(db_index=True, default=0)),
                ('level', models.IntegerField(db_index=True, default=1)),
                ('total_notes_created', models.IntegerField(default=0)),
                ('total_likes_received', models.IntegerField(default=0)),
                ('total_downloads_received', models.IntegerField(default=0)),
                ('last_daily_login', models.DateField(blank=True, null=True)),
                ('daily_login_streak', models.IntegerField(default=0)),
                ('profile_completed', models.BooleanField(default=False)),
                ('notes_created_today', models.IntegerField(default=0)),
                ('last_note_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_xp'],
            },
        ),
        migrations.DeleteModel(
            name='XPActivity',
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', '-created_at'], name='rewards_poi_user_id_f35609_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='rewards_poi_transac_01ad38_idx'),
        ),
    ]
